name: demo-action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Correct version for checkout
      - name: Run as sample job
        run: echo "This is a sample job running after code checkout"

      - name: Create a sample file
        run: echo "This is a sample file" > sample.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2  # Make sure this is correct version (v2 is latest for upload)
        with:
          name: sample-artifact
          path: sample.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v3  # Updated to v3
        with:
          name: sample-artifact
          path: ./downloaded-artifacts

      - name: Deploy artifact
        run: |
          echo "Deploying artifact"
          cat ./downloaded-artifacts/sample.txt
