name: demo-action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Checkout code

      - name: Run as sample job
        run: echo "This is a sample job running after code checkout"

      - name: Create a sample file
        run: echo "This is a sample file" > sample.txt  # Create sample file

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.0  # Correct version for upload
        with:
          name: sample-artifact
          path: sample.txt  # Path to the file to be uploaded

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Make sure deploy runs after build job
    steps:
      - uses: actions/checkout@v4.2.2  # Checkout code

      - name: Download artifact
        uses: actions/download-artifact@v4  # Correct version for download
        with:
          name: sample-artifact
          path: ./downloaded-artifacts  # Path to download the artifact

      - name: Deploy artifact
        run: |
          echo "Deploying artifact"
          cat ./downloaded-artifacts/sample.txt  # Output the file content to verify
