name : demo-actions

on: 
  # push:
  #   branches: master
  issues:
    types: [opened]
    
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: run a sample job
        run: echo Hello World
     -  name: Upload artifactes 
        uses: actions/upload-artifact@v4
        with:
         name: build-artifact
         path: ${{github.workspace}} # or path/to/artifact
  
    
