name : demo-actions

on: 
  push:
    branches: master

jobs:
  build:
    runs-on: ubantu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: run a sample job
        run: echo Hello World
      
  
    
